#!/bin/bash
# push

# Usage: push <repository>
#
# Pushes all the files inside <repository> in all the userhost.lst

repository="repository/"$1

display_usage() {
   echo -e "Usage: $0 <repository>"
   echo ""
   echo "Clones all files under repository/<repository> to the root of remote files."
   echo ""
   echo "options:"
   echo -e "\t<repository> Name of dir under repository folder to be cloned on remote machine."
   echo ""
}

if [ $# -lt 1 ];
then
    echo "Not enough arguments."
    display_usage
    exit 1
fi

if [ ! -d "$repository" ];
then
    echo "$1 is not a directory under repository/"
    display_usage
    exit 1
fi

echo "You are about to make changes in remote config files. "
read -p "Are you sure? (y/n) " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Nothing changed. Goodbye!"
    exit 0
fi

echo "Starting..."
for ip in `cat userhost.lst`; do
   toilet -f term -F border --gay  "$ip"
   rsync -avz --dry-run repository/ root@$ip:/
done
