#!/bin/bash
# gnome-shell

add-apt-repository ppa:gnome3-team/gnome3-staging -y
add-apt-repository ppa:gnome3-team/gnome3 -y
apt-get update
apt-get dist-upgrade -y
apt-get install gnome-shell -y
apt-get install ubuntu-gnome-desktop -y
apt-get install bijiben polari gnome-clocks gnome-weather gnome-maps gnome-music gnome-photos gnome-documents gnome-contacts epiphany-browser gnome-sushi gnome-boxes gnome-shell-extensions gnome-tweak-tool -y

