#!/bin/bash
# install-vnc

apt-get install -y x11vnc

x11vnc -storepasswd imtheboss /etc/x11vnc.pass

cat << EOF > /etc/init/x11vnc.conf
start on login-session-start

script

/usr/bin/x11vnc -xkb -forever -auth /var/run/lightdm/root/:0 -display :0 -rfbauth /etc/x11vnc.pass -rfbport 5900 -bg -o /var/log/x11vnc.log

end script
EOF
