#!/bin/bash
# copy_credentials

# Oct, 2015, txema.gonz@gmail.com
# GNU GENERAL PUBLIC LICENSE, Version 2

# Copies $credentials[=~/.ssh/id_rsa.pub] to
# the hosts provided through userhost.lst
# First param can provider remote user name user[=root]

# Usage:   ./copy_credentials [<user>=root]
# Example: ./copy_credentials bob

# Note: Point with userhost.lst (symbolic link) to a file
# containing the hosts

## Config Default Values
user="root"
credentials="~/.ssh/id_rsa.pub"

for ip in `cat userhost.lst`; do
    ssh-copy-id -i $credentials $user@$ip
done

