#!/bin/bash
# host-scan

# Execute as:
# $ setsid host-scan

# Little daemon to check net ips and mac addresses
# whithin all userhost.lst files in the system.

# Output written to /var/nettenance and
# /var/log/syslog

# Nov, 2015, txema.gonz@gmail.com
# GNU GENERAL PUBLIC LICENSE, Version 2


## Config Default Values
VERSION=1.0

. /usr/share/nettenance/general.sh


NAME=$(basename $0 )

close-fds() {
    eval exec {0..255}\>\&-
}

reload_config() {
   include_sanitized /etc/nettenance/host-scan.conf
   logger -t "$NAME" "Config Reload pid $BASHPID."
   logger -t "$NAME" "RELOAD_TIME=$RELOAD_TIME"
}

say_bye(){
	rm "/var/run/$NAME.pid"
	logger -t "$NAME" "Shutdown pid $BASHPID."
	exit 0
}

# Program start
host-scan-main_loop () {
	while [ 1 ]; do
		# Global files scan
		for lst in /etc/nettenance/hosts/*; do
		    local filename=global."${lst##*/}".macs
		    list-macs -H "$lst"> "scan/$filename"
		    chmod +r "scan/$filename"
            logger -t "$NAME" "List of macs [$filename] generated."
        done

        # Per user host files scan
		for home in $(home_dirs); do
			if [[ -d "$home/.nettenance/hosts" ]]; then
				for lst in "$home"/.nettenance/hosts/*; do
					local filename="${home##*/}"."${lst##*/}".macs
		            list-macs -H "$lst"> "scan/$filename"
		            chmod +r "scan/$filename"
                    logger -t "$NAME" "List of macs [$filename] generated."
                done
            fi
		done

        # Enable signals while sleeping
		sleep "$RELOAD_TIME" &
		wait
	done

}

# Program end
init () {
	logger -t "$NAME" "Nettenance Host Scan starting."
	trap 'reload_config' HUP
	trap 'say_bye' TERM

	# Ignored signals
	# Child dead uncaught because of sleep
	# trap ':' CHLD
	# Terminal signals
	trap ':' TTOU
	trap ':' TTIN
	trap ':' TSTP

	[[ -f "/var/run/$NAME.pid" ]] && echo "$NAME already in use." 1>&2 && exit 1
	
	umask 033
	mkdir -p /var/nettenance &> /dev/null
	cd /var/nettenance
	echo "$BASHPID" > "/var/run/$NAME.pid"

    # Ensure structure
    mkdir -p /var/nettenance/scan &> /dev/null
    chmod +x /var/nettenance/scan &> /dev/null
    mkdir -p /var/nettenance/known &> /dev/null
    chmod +x /var/nettenance/known &> /dev/null

	# Close standard fd
	close-fds

    logger -t "$NAME" "Nettenance Host Scan started. pid $BASHPID"
    reload_config
	# start daemon
    host-scan-main_loop
}

# Execute a subshell as a background
# fork of host-scan script.
# Run init within that subshell

# Note:
# As soon as host-scan ends, the
# subshell whit no parent is inherited
# by init. PPID=1

# Uncomment the following line to run it as a daemon
( init ) &
